# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4f949f7173d9fc5be05c4f4e794ce910be69a74aa7701583f759b0ab58d0480fd5ac015fa35d37b9168780f26eb69b1086a3a6b8e5ebd940188d7ff871fdbbd7

test:
  secret_key_base: bce5e6d5836950d5c1f087ef8b854e05873c669673a90eb8ca52d721f5c3881c8b1fe34038bd6b62f1a8af2548e3fb40938b5ea12e2ccf426e7c16ba6213eec5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
